#!/bin/env bash

black=#101112
white=#dfdfdf
bright_white=#ffffff
gray=#3f3f3f
bright_gray=#656565
red=#e60053
blue=#799df6
yellow=#fbdd91
pink=#f985e0
green=#6EF38B 
cyan=#00ffff
magenta=#ff00ff
purple=#756bb1
