[general]
notify = true

[keybindings]
"p" = "playpause"
"Shift+p" = "move playing"
"Shift+q" = "quit"
"gg" = "move top"
"Shift+g" = "move bottom"
"q" = "back"

[theme]
background = "#101112"
primary = "#FFFFFF"
secondary = "#DCDCDC"
title = "#1ED760"
playing = "#1ED760"
playing_selected = "#6EF38B"
playing_bg = "#121212"
highlight = "#799DF6"
highlight_bg = "#000000"
error = "#FFE4E4"
error_bg = "#E60053"
statusbar = "#101112"
statusbar_progress = "#FBDD91"
statusbar_bg = "#00AC4C"
cmdline = "#CBFFDE"
cmdline_bg = "#101112"
