#!/bin/env bash

# Inicializa o sxhkd 
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         0
bspc config window_gap          10

# for use with pywal
# source the colors.
#. "${HOME}/.cache/wal/colors.sh"
#
# set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"

# imports external rules
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules.sh

# Inicializa o bspswallow
pgrep bspswallow || bspswallow &

# Colors
bspc config normal_border_color "#101112"
bspc config focused_border_color "#756bb1"

bspc config split_ratio						0.50
bspc config top_padding 					32
bspc config bottom_padding 				34
bspc config left_padding 					8
bspc config right_padding 				8
bspc config borderless_monocle		false
bspc config gapless_monocle				false
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config automatic_scheme longest_side

# Opens applications in specific desktops
bspc rule -a Brave-browser desktop='6'
bspc rule -a LibreWolf desktop='6'
bspc rule -a TelegramDesktop desktop='5' state=floating
bspc rule -a zoom desktop='5'
bspc rule -a Steam desktop='4'
bspc rule -a Lutris desktop='4'
bspc rule -a dishonored.exe desktop='4'
bspc rule -a Sxiv state=floating
bspc rule -a mpv state=floating
bspc rule -a Connman-gtk state=floating
bspc rule -a lightcord desktop='5'
bspc rule -a Virt-manager desktop='4'
bspc rule -a Pcmanfm desktop='2'
bspc rule -a obs desktop='4'
bspc rule -a Galculator state=floating

bspc monitor -d 1 2 3 4 5 6

# Arruma o ponteiro do mouse
xsetroot -cursor_name left_ptr &

# Lança o polybar, e reinicia-o quando o bspwm é reiniciado
bash .config/polybar/launch.sh
