#!/bin/env bash

# uses lemonbar as the panel

# kills running lemonbar instances
pgrep -x lemonbar && killall -q lemonbar

dir=$(dirname $0)

# display options
font="-adobe-courier-medium-r-*-*-18-*-*-*-*-*-*-*"
dimensions=1904x30+8+4

# piping the info to the bar itself
. "$dir/feeder" | lemonbar -dp \
	-g ${dimensions} \
	-f ${font} \
	-f "Symbols Nerd Font"	\
	-F "#dfdfdf" \
	-B "#101112" \
	-u 3 \
	&
