#!/bin/env bash

# Simple X Hotkey Daemon config for use with dwm
# All hotkeys related to dwm are defined in its own config file.
# You can check my fork of dwm at https://github.com/Pinoinha/dwm-meu

# reload sxhkd
super + r
	pkill -USR1 -x sxhkd ; notify-send 'sxhkd' 'Reloaded config'

# -- Audio Control -- #

XF86AudioMute
	pulsemixer --toggle-mute; pkill -RTMIN+10 dwmblocks

XF86AudioLowerVolume
	pulsemixer --change-volume -5; pkill -RTMIN+10 dwmblocks

XF86AudioRaiseVolume
	pulsemixer --change-volume +5; pkill -RTMIN+10 dwmblocks

XF86AudioMicMute
	mic_check

XF86AudioPrev
	mpc prev

XF86AudioPlay
	mpc toggle

XF86AudioNext
	mpc next
	
# -- Brightness Control -- #

XF86MonBrightnessDown
	xbacklight -dec 10

XF86MonBrightnessUp
	xbacklight -inc 10
