#!/bin/bash

# Simple X Hotkey Daemon config

# --- WM-indepedent commands ---

# Reload sxhkd
super + r
	pkill -USR1 -x sxhkd; notify-send 'sxhkd' 'Reloaded config'

# Spawn terminal
super + Return
	st

# NOTA: O BSPWM vai matar todas as instâncias de alguns programas com essa opção
# Ex.: Firefox. Prefira o bspc node -c.
# Kill window
#super + w
#	xdotool getwindowfocus windowkill

# Lock the screen
super + shift + l
	xscreensaver-command --lock

# Open Firefox
super + b
	firefox

# Open qutebrowser
super + q
	qutebrowser

# Open rofi
super + d
	rofi -combi-modi window,drun,run,ssh -theme slate -font "gohu gohufont 11" -show combi -icon-theme "la-capitaine"

# Print selection with scrot
Print
	scrot -s "%Y-%m-%d_%w-%h.png" -e 'mv $f $HOME/Imagens/Prints'

# Media keys
XF86AudioLowerVolume
	pamixer @default_sink -d 5

XF86AudioRaiseVolume
	pamixer @default_sink -i 5

XF86AudioMute
	pamixer @default_sink -t

XF86AudioMicMute
	amixer set Capture toggle

# Backlight control
XF86MonBrightnessUp
	xbacklight -inc 10

XF86MonBrightnessUp
	xbacklight -dec 10

# --- BSPWM specific ---

# Kill X/Restart BSPWM
super + shift + {q,r}
	bspc {quit,wm -r}; notify-send 'bspwm' 'Restarted'

# Close window
super + w
	bspc node -c 

# Toggle Monocle Layout
super + shift + m
	bspc desktop -l next

# Set node state (change layout of individual node)
super + {t, shift + space, f}
	bspc node -t {tiled, \~floating, \~fullscreen}

# Move/resize floating windows with mouse
super + {left click, right click}
	bspc config {pointer_action1 move, pointer_action2 resize_side}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# Focus windows
super + {h,j,k,l}
	bspc node -f {west, south, north, east}

# Focus the next/previous window in the current desktop
super + {_,shift + }a
	bspc node -f {next,prev}.local.!hidden.window

# expand a window by moving one of its side outward
super + ctrl + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + ctrl + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# Focus on/send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# Focus the next/previous desktop in the current monitor
super + {n,m}
	bspc desktop -f {prev,next}.local

# Focus the last node/desktop
super + Tab
	bspc desktop -f last
