#!/bin/env bash

# Simple X Hotkey Daemon config

# -- WM-indepedent version -- #

# reload sxhkd
super + r
	pkill -USR1 -x sxhkd ; notify-send 'sxhkd' 'Reloaded config'

# spawn terminal
super + Return
	$TERMINAL

# spawn floating state
super + shift + Return
	$TERMINAL --class=flterm,flterm

# spawn vim
super + v
	$TERMINAL -e 'nvim'

# run terminal applications
super + e ; {1, 2, 3, 4, 5, 6}
	$TERMINAL -e {nnn, newsboat, htop, pulsemixer, calc}

# run gui applications
super + g ; {t, s, p}
	{telegram-desktop, steam, pcmanfm} && notify-send 'Programa inicializado' {'telegram', 'steam', 'pcmanfm'}

# run web browsers
super + b ; {1, 2, 3}
	{firefox, chromium, torbrowser-launcher}

# lock the screen
alt + shift + l
	slock

# dmenu based applications
super + d ; {1, 2, 3, 4}
	{dmenu_run -l 6, passmenu2, connect_wlan, ytfzf -D -s}

# -- Screenshots -- #

# print selection with scrot
@Print
	scrot -s -f '%Y-%m-%d_$wx$h.png' -e 'mv $f /home/math/Imagens/Prints'

# print current window with scrot
shift + @Print
	scrot -u '%Y-%m-%d_$wx$h.png' -e 'mv $f /home/math/Imagens/Prints'

# print entire screen with scrot
alt + @Print
	scrot "%Y-%m-%d_$wx$h.png" -e 'mv $f /home/math/Imagens/Prints'

# -- Audio Control -- #

XF86AudioMute
	pulsemixer --toggle-mute

shift + F1
	pulsemixer --toggle-mute

XF86AudioLowerVolume
	pulsemixer --change-volume -5

shift + F2
	pulsemixer --change-volume -5

XF86AudioRaiseVolume
	pulsemixer --change-volume +5

shift + F3
	pulsemixer --change-volume +5

XF86AudioMicMute
	mic_check

shift + F4
	mic_check

shift + F5
	mpc stop

XF86AudioPrev
	mpc prev

shift + F6
	mpc prev

XF86AudioPlay
	mpc toggle

shift + F7
	mpc toggle

XF86AudioNext
	mpc next

shift + F8
	mpc next
	
# -- Brightness Control -- #

XF86MonBrightnessDown
	xbacklight -dec 10

shift + F11
	xbacklight -dec 10

XF86MonBrightnessUp
	xbacklight -inc 10

shift + F12
	xbacklight -inc 10
