#!/bin/env bash

# Simple X Hotkey Daemon config

# --- WM-indepedent commands ---

# reload sxhkd
super + r
	pkill -USR1 -x sxhkd; notify-send 'sxhkd' 'Reloaded config'

# spawn terminal
super + {Return, KP_Enter}
	termite

# spawn terminal with vimwiki
super + v
	termite -e 'vim /home/math/vimwiki/index.md'

# lock the screen
alt + shift + l
	slock

# open Brave
ctrl + alt + b
	brave

# open Librewolf
ctrl + shift + b
	librewolf

# run dmenu
super + d
	dmenu_run

# run passemu
super + shift + d
	passmenu2

# run terminal applications
super + e ; {1, 2, 3, 4, 5}
	termite -e {lf-ueberzug, htop, ncmpcpp, newsboat, pulsemixer}

# print selection with scrot
@Print
	scrot -s "%Y-%m-%d_$wx$h.png" -e 'mv $f /home/math/Imagens/Prints'

# print current window with scrot
shift + @Print
	scrot -u "%Y-%m-%d_$wx$h.png" -e 'mv $f /home/math/Imagens/Prints'

# media keys
XF86AudioLowerVolume
	pulsemixer --change-volume -5

shift + F6
	pulsemixer --change-volume -5

XF86AudioRaiseVolume
	pulsemixer --change-volume +5

shift + F7
	pulsemixer --change-volume +5

XF86AudioMute
	pulsemixer --toggle-mute

shift + F1
	pulsemixer --toggle-mute

XF86AudioMicMute
	pulsemixer --id source-1 --toggle-mute

XF86AudioPlay
	mpc toggle

XF86AudioPrev
	mpc prev

XF86AudioNext
	mpc next

# backlight control
XF86MonBrightnessUp
	xbacklight -inc 5

shift + F12
	xbacklight -inc 5

XF86MonBrightnessUp
	xbacklight -dec 5

shift + F11
	xbacklight -dec 5

# --- BSPWM specific ---

# kill X/restart BSPWM
super + shift + {q,r}
	bspc {quit,wm -r}; notify-send 'bspwm' 'Restarted'

# close window
super + w
	bspc node -c 

# toggle Monocle layout
super + alt + m
	bspc desktop -l next

# set node tiling
super + t
	bspc node -t tiled

# set node pseudotiling
super + shift + t
	bspc node -t pseudo_tiled

# toggle node floating
super + space
	bspc node -t \~floating

# toggle node fullscreen
super + f
	bspc node -t \~fullscreen

# move/resize floating windows with mouse
super + {left click, right click}
	bspc config {pointer_action1 move, pointer_action2 resize_side}

# move a floating window
super + shift + {Left,Down,Up,Right}
	bspc node -v {-40 0,0 40,0 -40,40 0}

# toggle node sticky (in all desktops)
super + i
	bspc node -g sticky

# focus nodes
super + {h,j,k,l}
	bspc node -f {west, south, north, east}

# focus the next/previous node in the current desktop
super + {_,shift + }a
	bspc node -f {next,prev}.local.!hidden.window

# expand a node by moving two of its side outward
super + ctrl + l
	bspc node -z {bottom 0 20,right 20 0}

# contract a node by moving two of its side inward
super + ctrl + h
	bspc node -z {bottom 0 -20,right -20 0}

# focus on desktop
super + {1-9,0}
	bspc desktop -f '^{1-9,10}'

# send node to desktop and focus on it
super + shift + {1-9,0}
	bspc node -d '^{1-9,10}' --follow

# focus the next/previous desktop in the current monitor
super + {n,m}
	bspc desktop -f {prev,next}.local

# send node to prev desktop
super + shift + {n,m}
	bspc node -d {prev,next} --follow

# Focus the last node/desktop
super + Tab
	bspc desktop -f last

# preselect direction
super + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# swap node in direction
super + shift + {h,j,k,l}
	bspc node -s {west,south,north,east} --follow
