#!/bin/env bash

# prints current volume 

vol() {
	vol=$(pulsemixer --get-volume | awk ' { print $2 } ')
	mute=$(pulsemixer --get-mute)
	
	icon="" 
	
	# if muted
	[ $mute -eq 1 ] || [ $vol -eq 0 ] && icon="" && vol="mute"
	
	echo "$icon $vol%"
}

vol
