#!/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# adiciona padding nas bordas do monitor
#			 monitor	cima|direita|baixo|esquerda
hc pad 		0  		 40 		4 		 10 		4

# inicializa o sxhkd com a configuração do hlwm
pgrep -x sxhkd > /dev/null || sxhkd -c "$HOME/.config/sxhkd/hlwmKeys" &

# default layout
hc set default_frame_layout 1

# tags
#tag_names=( {1..6} )
tag_names=( "" "" "" "切" "" )
hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
done

# for configuring the mouse
Mod=Mod4

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#dfdfdf'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#e60053'
hc set frame_border_width 0
hc set always_show_frame on
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 4
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# --- Rules --- #
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=center

# give focus to terminal
hc rule class~'Alacritty' focus=on

# open applications in specific tags
hc rule class=firefoxdeveloperedition tag=
hc rule class=LibreWolf tag=
hc rule class=Chromium tag=
hc rule class=TelegramDesktop tag=切 floating=on 
hc rule class=zoom tag=切
hc rule class=Steam tag= floating=on
hc rule class=dishonored.exe tag=
hc rule class=Sxiv floating=on 
hc rule class=mpv floating=on 
hc rule class=Zathura floating=on 
hc rule class=Iwgtk floating=on 
hc rule class=lightcord tag=切
hc rule class=Virt-manager tag=
hc rule class=obs tag=
hc rule class=Galculator floating=on 

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# Unminimizes all minimized windows
hc keybind $Mod-Shift-b mktemp bool ISMINATT chain \
  . set_attr ISMINATT false \
  . foreach CLIENT clients. \
      sprintf MINATT "%c.minimized" CLIENT \
      sprintf TAGATT "%c.tag" CLIENT and \
         , compare MINATT "=" "true" \
         , substitute FOCUS "tags.focus.name" compare TAGATT "=" FOCUS \
         , set_attr ISMINATT true \
         , set_attr MINATT false \
   . and \
     , compare ISMINATT "=" false \
     , set_attr clients.focus.minimized true

# Lança o lemonbar, e reinicia-o quando o herbstluftwm é reiniciado
bash "$HOME/.config/lemonbar/launch"
